"""
Job Model
Stores job postings with required skills and AI-generated screening questions
"""
from sqlalchemy import Column, String, Integer, DateTime, Text, Enum as SQLEnum, Boolean, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector
from datetime import datetime
import enum

from app.db.database import Base


class JobStatus(str, enum.Enum):
    """Job posting status"""
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    CLOSED = "closed"
    FILLED = "filled"


class JobType(str, enum.Enum):
    """Employment type"""
    FULL_TIME = "full_time"
    PART_TIME = "part_time"
    CONTRACT = "contract"
    INTERNSHIP = "internship"
    FREELANCE = "freelance"


class ExperienceLevel(str, enum.Enum):
    """Required experience level"""
    ENTRY = "entry"  # 0-2 years
    MID = "mid"  # 2-5 years
    SENIOR = "senior"  # 5-10 years
    LEAD = "lead"  # 10+ years
    EXECUTIVE = "executive"  # C-level


class Job(Base):
    """Job posting model with AI-generated requirements and vector embeddings"""
    __tablename__ = "jobs"
    
    # Primary Fields
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False, index=True)
    company_name = Column(String(255), nullable=False)
    department = Column(String(100))
    
    # Job Details
    description = Column(Text, nullable=False)  # Full job description
    responsibilities = Column(JSONB)  # ["Design APIs", "Mentor juniors"]
    requirements = Column(JSONB)  # ["3+ years Python", "Experience with FastAPI"]
    nice_to_have = Column(JSONB)  # ["AWS certification", "Open source contributions"]
    
    # Classification
    status = Column(SQLEnum(JobStatus), default=JobStatus.DRAFT, index=True)
    job_type = Column(SQLEnum(JobType), default=JobType.FULL_TIME)
    experience_level = Column(SQLEnum(ExperienceLevel), default=ExperienceLevel.MID)
    
    # Location & Remote
    location = Column(String(255))  # "Bangalore, India"
    is_remote = Column(Boolean, default=False)
    remote_type = Column(String(50))  # "fully_remote", "hybrid", "onsite"
    
    # Compensation
    salary_min = Column(Integer)  # In INR or USD
    salary_max = Column(Integer)
    salary_currency = Column(String(3), default="INR")  # INR, USD
    equity = Column(Boolean, default=False)
    
    # Skills & Requirements
    required_skills = Column(JSONB)  # ["Python", "FastAPI", "PostgreSQL"]
    preferred_skills = Column(JSONB)  # ["Docker", "AWS", "Redis"]
    required_education = Column(String(100))  # "Bachelor's in CS or equivalent"
    required_experience_years = Column(Integer)  # Minimum years
    
    # AI/ML - Vector Embeddings (384 dimensions)
    job_description_embedding = Column(Vector(384))  # For semantic job matching
    skills_embedding = Column(Vector(384))  # For skills-based matching
    
    # AI-Generated Content
    ai_generated_questions = Column(JSONB)  # Screening questions generated by AI
    # Example: [{"question": "Explain FastAPI dependency injection", "type": "technical", "difficulty": "medium"}]
    
    # Hiring Pipeline
    total_applicants = Column(Integer, default=0)
    shortlisted_count = Column(Integer, default=0)
    rejected_count = Column(Integer, default=0)
    hired_count = Column(Integer, default=0)
    target_hires = Column(Integer, default=1)  # How many positions to fill
    
    # Posting Details
    posted_at = Column(DateTime)
    closes_at = Column(DateTime)  # Application deadline
    filled_at = Column(DateTime)  # When position was filled
    
    # Owner & Permissions
    created_by = Column(Integer, ForeignKey("users.id"))
    hiring_manager_id = Column(Integer, ForeignKey("users.id"))
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    applications = relationship("Application", back_populates="job", cascade="all, delete-orphan")
    created_by_user = relationship("User", foreign_keys=[created_by], back_populates="jobs_created")
    hiring_manager = relationship("User", foreign_keys=[hiring_manager_id], back_populates="jobs_managed")
    
    def __repr__(self):
        return f"<Job {self.title} at {self.company_name}>"
    
    @property
    def is_active(self) -> bool:
        """Check if job is actively accepting applications"""
        return self.status == JobStatus.ACTIVE and (self.closes_at is None or self.closes_at > datetime.utcnow())
    
    @property
    def salary_range_formatted(self) -> str:
        """Format salary range for display"""
        if self.salary_min and self.salary_max:
            return f"{self.salary_currency} {self.salary_min:,} - {self.salary_max:,}"
        elif self.salary_min:
            return f"{self.salary_currency} {self.salary_min:,}+"
        return "Not disclosed"
